### ISSUE TITLE
Documentation Effort - Document how the 2 lambdas are able to communicate with each other.

### ISSUE THREAD

**Issue by pouncilt** [byte-pushers/chucks-pick3#355]
I need to understand what I was doing wrong as to why the 2 Lambdas did communicate with each other after I added the RDS configuration.

**Comment by AmanAb428** [comment]
@pouncilt 

There was nothing related to code changes and any other configuration. It was related to the security group which was associated with lambda was not enabled with 443 port on outgoing request. AWS lambda request always requires the 443 port open to request the another lambda. 

To resolve the issue, First we have made these changes to allow AWS lambda to use public internet to call the another lambda. Please review the below cloud-formation changes.

```
ChucksPick3NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt: [ ChucksPick3ElasticIP, AllocationId ]
      SubnetId:
        Ref: PublicSubnet1
      Tags:
        - Key: Name
          Value: ChucksPick3NatGateway

 ChucksPick3InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: ChucksPick3InternetGateway
```

The, we have attached those gateway to the the our private/public routes as per below.

```
ChucksPick3PrivateRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - ChucksPick3NatGateway
      - ChucksPick3AttachInternetGateway
    Properties:
      RouteTableId:
        Ref: ChucksPick3PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: ChucksPick3NatGateway

ChucksPick3PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: ChucksPick3WSVpc
      Tags:
        - Key: Name
          Value: ChucksPick3PublicRouteTable
ChucksPick3PublicRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - ChucksPick3InternetGateway
      - ChucksPick3AttachInternetGateway
    Properties:
      RouteTableId:
        Ref: ChucksPick3PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: ChucksPick3InternetGateway
```

At last, VPC attachment is required to be attached with the Internet Gateway so it can make request on HTTPS (443). 

```
ChucksPick3AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: ChucksPick3WSVpc
      InternetGatewayId:
        Ref: ChucksPick3InternetGateway
```
